# Generated by Django 4.1.12 on 2023-10-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('Dosage', models.CharField(max_length=10)),
                ('Frequency', models.CharField(max_length=50)),
                ('Route', models.CharField(choices=[('oral', 'oral'), ('Intravenous', 'Intravenous'), ('Intramuscular', 'Intramuscular'), ('Subcutaneous', 'Subcutaneous'), ('Topical', 'Topical'), ('Inhalation', 'Inhalation')], max_length=50)),
                ('Duration', models.CharField(max_length=50)),
            ],
        ),
    ]
