<<<<<<< HEAD
# Generated by Django 4.1.12 on 2023-11-04 02:08
=======
# Generated by Django 4.1.12 on 2023-11-09 07:55
>>>>>>> 79599d2cde0f0f9c3ae17efbe816d69b234c1eb3

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_email', models.EmailField(max_length=255)),
                ('hospital_phone', models.BigIntegerField()),
                ('hospital_owner_name', models.CharField(max_length=255)),
                ('hospital_owner_phone', models.BigIntegerField()),
                ('hospital_owner_email', models.EmailField(max_length=255)),
                ('hospital_address', models.CharField(max_length=255)),
                ('hospital_city', models.CharField(max_length=255)),
                ('hospital_status', models.BooleanField()),
                ('hospital_type', models.CharField(max_length=255)),
                ('hospital_category', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
