# Generated by Django 4.1.12 on 2023-11-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='member_id',
            new_name='member',
        ),
    ]
