# Generated by Django 4.1.12 on 2023-11-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_member_id_user_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='member',
            new_name='member_id',
        ),
    ]
