# Generated by Django 4.1.12 on 2023-10-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='check_status',
            field=models.CharField(max_length=255),
        ),
    ]
