<<<<<<< HEAD
# Generated by Django 4.1.12 on 2023-11-04 02:07
=======
# Generated by Django 4.1.12 on 2023-11-09 07:54
>>>>>>> 79599d2cde0f0f9c3ae17efbe816d69b234c1eb3

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '__first__'),
        ('disease', '__first__'),
<<<<<<< HEAD
        ('doctor', '__first__'),
=======
>>>>>>> 79599d2cde0f0f9c3ae17efbe816d69b234c1eb3
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_time', models.TimeField()),
                ('appointment_date', models.DateField()),
                ('disease_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='disease.disease')),
                ('doctor_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
