<<<<<<< HEAD
# Generated by Django 4.1.12 on 2023-11-04 02:07
=======
# Generated by Django 4.1.12 on 2023-11-09 07:54
>>>>>>> 79599d2cde0f0f9c3ae17efbe816d69b234c1eb3

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=255)),
                ('disease_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
