<<<<<<< HEAD
# Generated by Django 4.1.12 on 2023-11-04 07:48
=======
# Generated by Django 4.1.12 on 2023-11-09 07:55
>>>>>>> 79599d2cde0f0f9c3ae17efbe816d69b234c1eb3

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField()),
                ('patient_address', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('patient_mobile', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
