# Generated by Django 4.1.12 on 2023-10-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_profile_picture',
        ),
    ]
