# Generated by Django 4.1.12 on 2023-11-18 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid Mobile number ', regex='^(?!.*(\\d)\\1{5})[0-9]+$/')]),
        ),
    ]
