# Generated by Django 4.1.12 on 2023-10-28 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_profile_picture', models.ImageField(upload_to='doctor_profile_picture/')),
                ('disease_specialist', models.CharField(max_length=255)),
                ('doctor_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('emergancy', 'Emergency')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
