# Generated by Django 4.1.12 on 2023-11-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
