"use client"
import CustomProvider from '@/redux/CustomProvider'
import { Auth0Provider } from '@auth0/auth0-react';

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Auth0Provider
        domain="dev-6g0pvxqgq73lne47.us.auth0.com"
        clientId="TDXoODFCGm4kqsJDZ9Yt0cPLUfigB3bE"
        authorizationParams={{
          redirect_uri: window.location.origin
        }}>

        <CustomProvider>

          <body className={inter.className}>{children}</body>
        </CustomProvider>
      </Auth0Provider>
    </html>
  )
}
